### ISSUE TITLE
Recipe AddCronTrigger creates empty expression

### ISSUE THREAD

**Issue by yeikel** [moderneinc/support-public#26]
Sample configuration : 

```yml

type: specs.openrewrite.org/v1beta/recipe
name: org.yeikel.MyCustomRecipe
displayName: My custom recipe
description: Fix all the things.
recipeList:
  - org.openrewrite.github.AddCronTrigger:
      cron: 5 4 * * *
```

The input to `cron` does not seem to matter as the other expressions also create the same problem

![image](https://user-images.githubusercontent.com/8935151/226775005-71ba9407-e65e-479f-aba3-80888566d032.png)

```

  @Test
  fun netflixruntimeHealth() = assertUnchanged(
    moderneAstLink = "https://api.public.moderne.io/worker/ast/file?path=Netflix%2Fruntime-health&origin=github.com&branch=master&changeset=89a897ad7958551f439fe019d5436665e3a510a0&filePath="
  )
  
```
